spring:
  profiles:
    active: local
server:
  port: 8081

---
spring:
  config:
    activate:
      on-profile: local
  kafka:
    consumer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      group-id: transactions-listener-group
      fetch-min-size: 1024
      fetch-max-wait: 500
      max-poll-records: 500
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.UUIDDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: "*"
        spring.json.use.type.headers: false
        spring.json.value.default.type: transaction.transaction_consumer.entity.Transaction
    listener:
      ack-mode: manual_immediate
  datasource:
    url: jdbc:mysql://localhost:3306/transactions
    username: mhg1503
    password: 1503
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
